### ISSUE TITLE
Zim plaintext is hardly readable

### ISSUE THREAD

**Issue by nicorikken** [schemar/solarc-theme#28]
I use solar-theme version 800c997-1 on Ubuntu using Regolith.
I use Zim desktop wiki, which has the option of plaintext preformatted text.
Normally this is a lighter grey compared to the regular black. Now it is also a slightly different color, but hardly readable against the background:

![image](https://user-images.githubusercontent.com/7458098/60494439-1e1df380-9caf-11e9-97ad-07beac6cf6d6.png)

I noticed the recent update to GTK2 theme #24 which might be helpful here.
How could I identify the color in use here, to propose a change?

Thanks for developing this theme!

**Comment by Omnikron13** [comment]
Hm... That version is quite out of date at this point. First things first I think Regolith would need to update their PPA to use a more recent version as I've made a lot of changes to the colours since that commit, and I'm not sure how it will look with the most recent version.

That aside trying to work out what colour is being used from that screenshot looks like it could be tricky because of subpixel rendering. Probably the easiest workaround would be if you can have it render a blocky character like the unicode full block (█) which would show the colour getting used a lot more clearly.

If you're able to test it with the latest version of solarc from git that'd be helpful, and you might want to open an issue with Regolith suggesting they update as there really have been quite a few changes since the version they're using.

**Comment by Omnikron13** [comment]
I've done a little testing & digging and it seems this issue is with any dark theme and Zim; the colour being used isn't sourced at all from the theme but is set by Zim itself.

The colour it is using is `#2e3436`, which traces back to `/usr/share/zim/style.conf`, (or your personal copy in `${XDG_CONFIG_HOME}/zim/style.conf` once Zim has been first run):

```
# Verbatim gets a slightly different color to distinguish easier
# used the dark "aluminium" color from the Tango palette.

[Tag code]
foreground = #2e3436
family = monospace
#wrap-mode = none

[Tag pre]
# This style is used for multi-line verbatim blocks
foreground = #2e3436
family    = monospace
wrap-mode = none
indent    = 20
```

Edit your personal copy to your liking and you'll get good contrast in SolArc. =)

**Comment by Omnikron13** [comment]
Closing as this isn't an issue with SolArc.
